2.2 Website. User creation works
Fixed a problem that caused a
TypeError: Cannot destructure property 'password_' of 'req.body' as it is undefined
Problem whas a missing app.use(express.urlencoded({extended: true})); line